application: html5gamejam-1163
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*\.(gif|png|jpg|html|js|css|eot|svg|ttf|woff|ico))
  static_files: \1
  upload: (.*\.(gif|png|jpg|html|js|css|eot|svg|ttf|woff|ico))
