application: html5gamejamnl
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*\.(gif|png|jpg|html|js|css|eot|svg|ttf|woff|ico))
  static_files: \1
  upload: (.*\.(gif|png|jpg|html|js|css|eot|svg|ttf|woff|ico))
